### ISSUE TITLE
add login customizer plugin + tweet old post

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/minimagazine#13]
add login customizer plugin + tweet old post.

@rodica-andronache in principiu toate temele free ar trebui sa aibe 1-2 pluginuri sugerate, daca nu au, ar trebui adaugate. La fel cel putin o data pe luna ar trebui sa mai facem o mica chestie la fiecare tema free ca sa putem trimite update.

Chiar si un mic fix gen screenshot, descriere, css/html/php

**Comment by rodica-andronache** [comment]
@ineagu ok, o sa incerc sa tin evidenta cu asta. Pana acum am incercat sa verific sa fie facute la toate documentatia si demo-ul.

**Comment by ineagu** [comment]
Ok, dupa ce rezolvam cu alea putem pregati un proces prin care sa trimitem cate un update lunar
